version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Updated from 3000:3000 to 80:80 for Nginx
    environment:
      - REACT_APP_API_URL=https://smartname.lk/api
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.huggingface:/root/.huggingface

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: smartname